apiVersion: v1
kind: Service
metadata:
  name: emqx-public
spec:
  ports:
  - name: emqx-dashboard
    port: 32333
    targetPort:  emqx-dashboard
    protocol: TCP
  - name: emqx-mqtt-ssl
    port: 8883
    targetPort:  emqx-mqtt-ssl
    protocol: TCP
  - name: emqx-mqtt
    port: 1883
    targetPort:  emqx-mqtt
    protocol: TCP
  selector:
    app: emqx
  type: LoadBalancer