apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  ports:
  - port: 32333
    nodePort: 32333
    targetPort:  emqx-dashboard
    protocol: TCP
  - port: 8883
    nodePort: 8883
    targetPort:  emqx-mqtt-ssl
    protocol: TCP
  - port: 1883
    nodePort: 1883
    targetPort:  emqx-mqtt
    protocol: TCP
  selector:
    app: emqx
  type: NodePort