apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqx
  namespace: emqx

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: emqx
subjects:
- kind: ServiceAccount
  name: emqx
  namespace: emqx
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
