apiVersion: v1
data:
  .dockercfg: eyJoYXJib3IucGF0aGFvaW50ZXJuYWwuY29tIjp7InVzZXJuYW1lIjoiZmFydWsiLCJwYXNzd29yZCI6IkNzRTA4MzA0OSIsImVtYWlsIjoiZmFydWtAcGF0aGFvLmNvbSIsImF1dGgiOiJabUZ5ZFdzNlEzTkZNRGd6TURRNSJ9fQ==
kind: Secret
metadata:
  name: regsecret
  namespace: boom
type: kubernetes.io/dockercfg
