apiVersion: v1
kind: ServiceAccount
metadata:
  name: emqtt
  namespace: emqtt

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: emqtt
subjects:
- kind: ServiceAccount
  name: emqtt
  namespace: emqtt
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io